Abnormally high gas fee triggered in Metamask on YFI > BNT swap #807
bancorprotocol/webapp pull request #1001
Opened 2021-02-11 03:15 UTC by Eratos1122

2021-02-11 05:54 UTC, Velua requested changes
See my comment in the original issue. 

If we were to use this logic it would need to be done using BigNumber as numbers could be entered into this textbox which outgrows numbers in native JavaScript.

2021-02-11 14:06 UTC, Eratos1122 commented
`Number` can be used as a bigNumber
And the current rate is being calculated using the `Number`

2021-02-11 18:17 UTC, Velua commented
@pingustar please review.

2021-02-14 00:33 UTC, Velua approved these changes

2021-02-15 13:42 UTC, merged