Protected table filters
bancorprotocol/webapp pull request #1004
Opened 2021-02-11 13:50 UTC by Ran73Cohen

#630

2021-02-15 10:59 UTC, Velua commented on src/views/ProtectionHome.vue
> +        x => x.fullCoverage - now < 0
Let's adopt a more consistent approach by using some of the DayJS methods we've been using elsewhere. 

An example
```
  const now = dayjs();
  const availableClaims = this.lockedBalancesArr
      .filter(balance => dayjs.unix(balance.expirationTime).isBefore(now))
```

2021-02-15 11:05 UTC, Velua commented on src/views/ProtectionHome.vue
> +      )
Lets use the lodash function ```uniq``` or ```uniqWith```

2021-02-15 11:05 UTC, Velua commented on src/views/ProtectionHome.vue
> +        poolId: value.poolId
Using indexes as IDs in lists can defeat the purpose of giving array items IDs in the first place, as mutating the array doesn't help with any diffing in the background. 

We know a ```positionId``` will be unique, can we use that as an ID instead?

2021-02-16 00:17 UTC, Velua requested changes

2021-02-16 00:17 UTC, Velua commented on src/components/common/ContentBlock.vue
> +          :key="index"
Cannot use an index as a key, use an ID property.

2021-02-16 00:17 UTC, Velua commented on src/components/common/ContentBlock.vue
>            @click="() => (dropdown.selectedIndex = index)"
Can we achieve this with just 
```suggestion
          @click="dropdown.selectedIndex = index"
```

Don't usually need to do anonymous functions in Vue as much as React.

2021-02-16 00:17 UTC, Velua commented on src/views/ProtectionHome.vue
>        ]
Just map over this with ```map(x => ({...x, id: x.title }))``` if you need an ID.

2021-02-16 00:24 UTC, Velua commented on src/views/ProtectionHome.vue
> +        poolId: value.poolId
```suggestion
        title: buildPoolName(value.poolId),
        poolId: value.poolId,
        id: value.id
```

2021-03-09 17:08 UTC, Ran73Cohen commented
Continue in #1170

2021-03-09 17:08 UTC, closed without merging