Upper Case
bancorprotocol/webapp pull request #1137
Opened 2021-03-04 12:20 UTC by Ran73Cohen

UPPER CASE BAD!
Camel Case Good :D

2021-03-04 12:43 UTC, Meytal2021 commented
@meytal2021

2021-03-08 14:01 UTC, ashachaf commented
looks good to me.

2021-03-09 10:09 UTC, pingustar requested changes
missing cleanup of empty class attributes

2021-03-09 10:09 UTC, pingustar commented on src/components/layout/SettingsMenu.vue
> +        class=""
can be removed

2021-03-09 10:09 UTC, pingustar commented on src/components/modals/ModalVoteDetails.vue
> +        <div class="" :class="getVoteClass(data.value)">
^

2021-03-09 10:09 UTC, pingustar commented on src/components/vote/proposals/OpenProposals.vue
> +                  <span class="">{{ item.votes.voted }}</span>
^

2021-03-09 10:12 UTC, Ran73Cohen commented
> 
> 
> missing cleanup of empty class attributes

Yeah I noticed it and forgot to fix :|

2021-03-09 12:41 UTC, pingustar approved these changes

2021-03-21 14:52 UTC, ashachaf commented
what is holding this off from being pushed to prod?

2021-04-04 10:19 UTC, Ran73Cohen commented
@Meytal2021 Can you review the new font sizes?

2021-04-22 07:47 UTC, merged